name: Run Tests

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test ${{ matrix.os }}-${{ matrix.pyver }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        pyver: ['3.13', '3.12', '3.11', '3.10', '3.9', '3.8', '3.7']
        arch: [x64]
        include:
          - os: windows-latest
            pyver: '3.13'
            arch: x86
          - os: ubuntu-latest
            pyver: '3.13'
            arch: x64
          - os: macos-latest
            pyver: '3.13'
            arch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.pyver }}
          architecture: ${{ matrix.arch }}

      - name: Install package
        run: pip install .[adhoc_ssl]

      - name: Run tests
        run: python -m unittest

      - name: Ensure all dependency can be installed
        run: pip install -r requirements-dev.txt
